apiVersion: v1
kind: Namespace
metadata:
  name: k8s-web-sample
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: k8s-web-sample
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: g23988/k8s-web-sample-api:latest 
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: k8s-web-sample
spec:
  selector:
    app: api
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "k8s-web-ingress"
  namespace: "k8s-web-sample"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
    app: k8s-web-ingress
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: "api-service"
              servicePort: 80
